name: stopgrinding
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  launch_at_startup: ^0.5.1
  package_info_plus: ^9.0.1
  tray_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.3
  flutter_lints: ^5.0.0
  pigeon: ^26.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/overlays/neko_cat/
    - macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png