// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

enum InteractionModeDto { blocking, passthrough }

enum FullscreenModeDto { disabled, enabled }

enum MonitorScopeDto { allDisplays }

enum DismissPolicyTypeDto { timedOnly, doubleClickAnywhere, doubleClickCat }

enum OverlayStateDto {
  idle,
  scheduled,
  preparing,
  visible,
  dismissed,
  cooldown,
  paused,
}

enum OverlayDismissReasonDto {
  timeout,
  userGesture,
  replaced,
  hiddenByApp,
  failed,
}

class OverlaySettingsDto {
  OverlaySettingsDto({
    required this.intervalMillis,
    required this.durationMillis,
    required this.interactionMode,
    required this.fullscreenMode,
    required this.monitorScope,
    required this.dismissPolicyType,
    required this.allowEarlyDismiss,
  });

  int intervalMillis;

  int durationMillis;

  InteractionModeDto interactionMode;

  FullscreenModeDto fullscreenMode;

  MonitorScopeDto monitorScope;

  DismissPolicyTypeDto dismissPolicyType;

  bool allowEarlyDismiss;

  List<Object?> _toList() {
    return <Object?>[
      intervalMillis,
      durationMillis,
      interactionMode,
      fullscreenMode,
      monitorScope,
      dismissPolicyType,
      allowEarlyDismiss,
    ];
  }

  Object encode() {
    return _toList();
  }

  static OverlaySettingsDto decode(Object result) {
    result as List<Object?>;
    return OverlaySettingsDto(
      intervalMillis: result[0]! as int,
      durationMillis: result[1]! as int,
      interactionMode: result[2]! as InteractionModeDto,
      fullscreenMode: result[3]! as FullscreenModeDto,
      monitorScope: result[4]! as MonitorScopeDto,
      dismissPolicyType: result[5]! as DismissPolicyTypeDto,
      allowEarlyDismiss: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OverlaySettingsDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class OverlayRequestDto {
  OverlayRequestDto({
    required this.requestId,
    required this.settings,
    this.triggeredAtEpochMillis,
  });

  String requestId;

  OverlaySettingsDto settings;

  int? triggeredAtEpochMillis;

  List<Object?> _toList() {
    return <Object?>[requestId, settings, triggeredAtEpochMillis];
  }

  Object encode() {
    return _toList();
  }

  static OverlayRequestDto decode(Object result) {
    result as List<Object?>;
    return OverlayRequestDto(
      requestId: result[0]! as String,
      settings: result[1]! as OverlaySettingsDto,
      triggeredAtEpochMillis: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OverlayRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class HideOverlayRequestDto {
  HideOverlayRequestDto({required this.reason, this.requestedAtEpochMillis});

  OverlayDismissReasonDto reason;

  int? requestedAtEpochMillis;

  List<Object?> _toList() {
    return <Object?>[reason, requestedAtEpochMillis];
  }

  Object encode() {
    return _toList();
  }

  static HideOverlayRequestDto decode(Object result) {
    result as List<Object?>;
    return HideOverlayRequestDto(
      reason: result[0]! as OverlayDismissReasonDto,
      requestedAtEpochMillis: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HideOverlayRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class DisplayTargetDto {
  DisplayTargetDto({
    required this.id,
    required this.name,
    required this.isPrimary,
  });

  String id;

  String name;

  bool isPrimary;

  List<Object?> _toList() {
    return <Object?>[id, name, isPrimary];
  }

  Object encode() {
    return _toList();
  }

  static DisplayTargetDto decode(Object result) {
    result as List<Object?>;
    return DisplayTargetDto(
      id: result[0]! as String,
      name: result[1]! as String,
      isPrimary: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DisplayTargetDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class OverlaySessionDto {
  OverlaySessionDto({
    required this.id,
    required this.startedAtEpochMillis,
    required this.displays,
  });

  String id;

  int startedAtEpochMillis;

  List<DisplayTargetDto> displays;

  List<Object?> _toList() {
    return <Object?>[id, startedAtEpochMillis, displays];
  }

  Object encode() {
    return _toList();
  }

  static OverlaySessionDto decode(Object result) {
    result as List<Object?>;
    return OverlaySessionDto(
      id: result[0]! as String,
      startedAtEpochMillis: result[1]! as int,
      displays: (result[2] as List<Object?>?)!.cast<DisplayTargetDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OverlaySessionDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class OverlayDismissedDto {
  OverlayDismissedDto({
    required this.sessionId,
    required this.reason,
    required this.dismissedAtEpochMillis,
  });

  String sessionId;

  OverlayDismissReasonDto reason;

  int dismissedAtEpochMillis;

  List<Object?> _toList() {
    return <Object?>[sessionId, reason, dismissedAtEpochMillis];
  }

  Object encode() {
    return _toList();
  }

  static OverlayDismissedDto decode(Object result) {
    result as List<Object?>;
    return OverlayDismissedDto(
      sessionId: result[0]! as String,
      reason: result[1]! as OverlayDismissReasonDto,
      dismissedAtEpochMillis: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OverlayDismissedDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class OverlayErrorDto {
  OverlayErrorDto({required this.code, required this.message});

  String code;

  String message;

  List<Object?> _toList() {
    return <Object?>[code, message];
  }

  Object encode() {
    return _toList();
  }

  static OverlayErrorDto decode(Object result) {
    result as List<Object?>;
    return OverlayErrorDto(
      code: result[0]! as String,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OverlayErrorDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class DisplayTopologyDto {
  DisplayTopologyDto({
    required this.displays,
    required this.changedAtEpochMillis,
  });

  List<DisplayTargetDto> displays;

  int changedAtEpochMillis;

  List<Object?> _toList() {
    return <Object?>[displays, changedAtEpochMillis];
  }

  Object encode() {
    return _toList();
  }

  static DisplayTopologyDto decode(Object result) {
    result as List<Object?>;
    return DisplayTopologyDto(
      displays: (result[0] as List<Object?>?)!.cast<DisplayTargetDto>(),
      changedAtEpochMillis: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DisplayTopologyDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class OverlayStatusDto {
  OverlayStatusDto({
    required this.state,
    this.activeSession,
    this.nextTriggerAtEpochMillis,
  });

  OverlayStateDto state;

  OverlaySessionDto? activeSession;

  int? nextTriggerAtEpochMillis;

  List<Object?> _toList() {
    return <Object?>[state, activeSession, nextTriggerAtEpochMillis];
  }

  Object encode() {
    return _toList();
  }

  static OverlayStatusDto decode(Object result) {
    result as List<Object?>;
    return OverlayStatusDto(
      state: result[0]! as OverlayStateDto,
      activeSession: result[1] as OverlaySessionDto?,
      nextTriggerAtEpochMillis: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OverlayStatusDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is InteractionModeDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is FullscreenModeDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is MonitorScopeDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is DismissPolicyTypeDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is OverlayStateDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is OverlayDismissReasonDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is OverlaySettingsDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is OverlayRequestDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is HideOverlayRequestDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is DisplayTargetDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is OverlaySessionDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is OverlayDismissedDto) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is OverlayErrorDto) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is DisplayTopologyDto) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is OverlayStatusDto) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : InteractionModeDto.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : FullscreenModeDto.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : MonitorScopeDto.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DismissPolicyTypeDto.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : OverlayStateDto.values[value];
      case 134:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : OverlayDismissReasonDto.values[value];
      case 135:
        return OverlaySettingsDto.decode(readValue(buffer)!);
      case 136:
        return OverlayRequestDto.decode(readValue(buffer)!);
      case 137:
        return HideOverlayRequestDto.decode(readValue(buffer)!);
      case 138:
        return DisplayTargetDto.decode(readValue(buffer)!);
      case 139:
        return OverlaySessionDto.decode(readValue(buffer)!);
      case 140:
        return OverlayDismissedDto.decode(readValue(buffer)!);
      case 141:
        return OverlayErrorDto.decode(readValue(buffer)!);
      case 142:
        return DisplayTopologyDto.decode(readValue(buffer)!);
      case 143:
        return OverlayStatusDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class OverlayHostApi {
  /// Constructor for [OverlayHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OverlayHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.stopgrinding.OverlayHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> showOverlay(OverlayRequestDto request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.stopgrinding.OverlayHostApi.showOverlay$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> hideOverlay(HideOverlayRequestDto request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.stopgrinding.OverlayHostApi.hideOverlay$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateSettings(OverlaySettingsDto settings) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.stopgrinding.OverlayHostApi.updateSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[settings],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> refreshDisplays() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.stopgrinding.OverlayHostApi.refreshDisplays$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<OverlayStatusDto> getOverlayStatus() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.stopgrinding.OverlayHostApi.getOverlayStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as OverlayStatusDto?)!;
    }
  }
}

abstract class OverlayFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onOverlayShown(OverlaySessionDto session);

  void onOverlayDismissed(OverlayDismissedDto event);

  void onOverlayFailed(OverlayErrorDto error);

  void onDisplayTopologyChanged(DisplayTopologyDto topology);

  static void setUp(
    OverlayFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayShown$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayShown was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final OverlaySessionDto? arg_session =
              (args[0] as OverlaySessionDto?);
          assert(
            arg_session != null,
            'Argument for dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayShown was null, expected non-null OverlaySessionDto.',
          );
          try {
            api.onOverlayShown(arg_session!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayDismissed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayDismissed was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final OverlayDismissedDto? arg_event =
              (args[0] as OverlayDismissedDto?);
          assert(
            arg_event != null,
            'Argument for dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayDismissed was null, expected non-null OverlayDismissedDto.',
          );
          try {
            api.onOverlayDismissed(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayFailed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayFailed was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final OverlayErrorDto? arg_error = (args[0] as OverlayErrorDto?);
          assert(
            arg_error != null,
            'Argument for dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayFailed was null, expected non-null OverlayErrorDto.',
          );
          try {
            api.onOverlayFailed(arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onDisplayTopologyChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onDisplayTopologyChanged was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final DisplayTopologyDto? arg_topology =
              (args[0] as DisplayTopologyDto?);
          assert(
            arg_topology != null,
            'Argument for dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onDisplayTopologyChanged was null, expected non-null DisplayTopologyDto.',
          );
          try {
            api.onDisplayTopologyChanged(arg_topology!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
