// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsoverlay_api(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsoverlay_api(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsoverlay_api(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashoverlay_api(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashoverlay_api(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashoverlay_api(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum InteractionModeDto: Int {
  case blocking = 0
  case passthrough = 1
}

enum FullscreenModeDto: Int {
  case disabled = 0
  case enabled = 1
}

enum MonitorScopeDto: Int {
  case allDisplays = 0
}

enum DismissPolicyTypeDto: Int {
  case timedOnly = 0
  case doubleClickAnywhere = 1
  case doubleClickCat = 2
}

enum OverlayStateDto: Int {
  case idle = 0
  case scheduled = 1
  case preparing = 2
  case visible = 3
  case dismissed = 4
  case cooldown = 5
  case paused = 6
}

enum OverlayDismissReasonDto: Int {
  case timeout = 0
  case userGesture = 1
  case replaced = 2
  case hiddenByApp = 3
  case failed = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlaySettingsDto: Hashable {
  var intervalMillis: Int64
  var durationMillis: Int64
  var interactionMode: InteractionModeDto
  var fullscreenMode: FullscreenModeDto
  var monitorScope: MonitorScopeDto
  var dismissPolicyType: DismissPolicyTypeDto
  var allowEarlyDismiss: Bool
  var selectedOverlayId: String
  var selectedOverlayAssetPath: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlaySettingsDto? {
    let intervalMillis = pigeonVar_list[0] as! Int64
    let durationMillis = pigeonVar_list[1] as! Int64
    let interactionMode = pigeonVar_list[2] as! InteractionModeDto
    let fullscreenMode = pigeonVar_list[3] as! FullscreenModeDto
    let monitorScope = pigeonVar_list[4] as! MonitorScopeDto
    let dismissPolicyType = pigeonVar_list[5] as! DismissPolicyTypeDto
    let allowEarlyDismiss = pigeonVar_list[6] as! Bool
    let selectedOverlayId = pigeonVar_list[7] as! String
    let selectedOverlayAssetPath = pigeonVar_list[8] as! String

    return OverlaySettingsDto(
      intervalMillis: intervalMillis,
      durationMillis: durationMillis,
      interactionMode: interactionMode,
      fullscreenMode: fullscreenMode,
      monitorScope: monitorScope,
      dismissPolicyType: dismissPolicyType,
      allowEarlyDismiss: allowEarlyDismiss,
      selectedOverlayId: selectedOverlayId,
      selectedOverlayAssetPath: selectedOverlayAssetPath
    )
  }
  func toList() -> [Any?] {
    return [
      intervalMillis,
      durationMillis,
      interactionMode,
      fullscreenMode,
      monitorScope,
      dismissPolicyType,
      allowEarlyDismiss,
      selectedOverlayId,
      selectedOverlayAssetPath,
    ]
  }
  static func == (lhs: OverlaySettingsDto, rhs: OverlaySettingsDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlayRequestDto: Hashable {
  var requestId: String
  var settings: OverlaySettingsDto
  var triggeredAtEpochMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlayRequestDto? {
    let requestId = pigeonVar_list[0] as! String
    let settings = pigeonVar_list[1] as! OverlaySettingsDto
    let triggeredAtEpochMillis: Int64? = nilOrValue(pigeonVar_list[2])

    return OverlayRequestDto(
      requestId: requestId,
      settings: settings,
      triggeredAtEpochMillis: triggeredAtEpochMillis
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      settings,
      triggeredAtEpochMillis,
    ]
  }
  static func == (lhs: OverlayRequestDto, rhs: OverlayRequestDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HideOverlayRequestDto: Hashable {
  var reason: OverlayDismissReasonDto
  var requestedAtEpochMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HideOverlayRequestDto? {
    let reason = pigeonVar_list[0] as! OverlayDismissReasonDto
    let requestedAtEpochMillis: Int64? = nilOrValue(pigeonVar_list[1])

    return HideOverlayRequestDto(
      reason: reason,
      requestedAtEpochMillis: requestedAtEpochMillis
    )
  }
  func toList() -> [Any?] {
    return [
      reason,
      requestedAtEpochMillis,
    ]
  }
  static func == (lhs: HideOverlayRequestDto, rhs: HideOverlayRequestDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DisplayTargetDto: Hashable {
  var id: String
  var name: String
  var isPrimary: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DisplayTargetDto? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let isPrimary = pigeonVar_list[2] as! Bool

    return DisplayTargetDto(
      id: id,
      name: name,
      isPrimary: isPrimary
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      isPrimary,
    ]
  }
  static func == (lhs: DisplayTargetDto, rhs: DisplayTargetDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlaySessionDto: Hashable {
  var id: String
  var startedAtEpochMillis: Int64
  var displays: [DisplayTargetDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlaySessionDto? {
    let id = pigeonVar_list[0] as! String
    let startedAtEpochMillis = pigeonVar_list[1] as! Int64
    let displays = pigeonVar_list[2] as! [DisplayTargetDto]

    return OverlaySessionDto(
      id: id,
      startedAtEpochMillis: startedAtEpochMillis,
      displays: displays
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      startedAtEpochMillis,
      displays,
    ]
  }
  static func == (lhs: OverlaySessionDto, rhs: OverlaySessionDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlayDismissedDto: Hashable {
  var sessionId: String
  var reason: OverlayDismissReasonDto
  var dismissedAtEpochMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlayDismissedDto? {
    let sessionId = pigeonVar_list[0] as! String
    let reason = pigeonVar_list[1] as! OverlayDismissReasonDto
    let dismissedAtEpochMillis = pigeonVar_list[2] as! Int64

    return OverlayDismissedDto(
      sessionId: sessionId,
      reason: reason,
      dismissedAtEpochMillis: dismissedAtEpochMillis
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      reason,
      dismissedAtEpochMillis,
    ]
  }
  static func == (lhs: OverlayDismissedDto, rhs: OverlayDismissedDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlayErrorDto: Hashable {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlayErrorDto? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return OverlayErrorDto(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: OverlayErrorDto, rhs: OverlayErrorDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DisplayTopologyDto: Hashable {
  var displays: [DisplayTargetDto]
  var changedAtEpochMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DisplayTopologyDto? {
    let displays = pigeonVar_list[0] as! [DisplayTargetDto]
    let changedAtEpochMillis = pigeonVar_list[1] as! Int64

    return DisplayTopologyDto(
      displays: displays,
      changedAtEpochMillis: changedAtEpochMillis
    )
  }
  func toList() -> [Any?] {
    return [
      displays,
      changedAtEpochMillis,
    ]
  }
  static func == (lhs: DisplayTopologyDto, rhs: DisplayTopologyDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlayStatusDto: Hashable {
  var state: OverlayStateDto
  var activeSession: OverlaySessionDto? = nil
  var nextTriggerAtEpochMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlayStatusDto? {
    let state = pigeonVar_list[0] as! OverlayStateDto
    let activeSession: OverlaySessionDto? = nilOrValue(pigeonVar_list[1])
    let nextTriggerAtEpochMillis: Int64? = nilOrValue(pigeonVar_list[2])

    return OverlayStatusDto(
      state: state,
      activeSession: activeSession,
      nextTriggerAtEpochMillis: nextTriggerAtEpochMillis
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      activeSession,
      nextTriggerAtEpochMillis,
    ]
  }
  static func == (lhs: OverlayStatusDto, rhs: OverlayStatusDto) -> Bool {
    return deepEqualsoverlay_api(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashoverlay_api(value: toList(), hasher: &hasher)
  }
}

private class OverlayApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return InteractionModeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FullscreenModeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MonitorScopeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DismissPolicyTypeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OverlayStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OverlayDismissReasonDto(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return OverlaySettingsDto.fromList(self.readValue() as! [Any?])
    case 136:
      return OverlayRequestDto.fromList(self.readValue() as! [Any?])
    case 137:
      return HideOverlayRequestDto.fromList(self.readValue() as! [Any?])
    case 138:
      return DisplayTargetDto.fromList(self.readValue() as! [Any?])
    case 139:
      return OverlaySessionDto.fromList(self.readValue() as! [Any?])
    case 140:
      return OverlayDismissedDto.fromList(self.readValue() as! [Any?])
    case 141:
      return OverlayErrorDto.fromList(self.readValue() as! [Any?])
    case 142:
      return DisplayTopologyDto.fromList(self.readValue() as! [Any?])
    case 143:
      return OverlayStatusDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class OverlayApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InteractionModeDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? FullscreenModeDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MonitorScopeDto {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? DismissPolicyTypeDto {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? OverlayStateDto {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? OverlayDismissReasonDto {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? OverlaySettingsDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? OverlayRequestDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? HideOverlayRequestDto {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? DisplayTargetDto {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? OverlaySessionDto {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? OverlayDismissedDto {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? OverlayErrorDto {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? DisplayTopologyDto {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? OverlayStatusDto {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class OverlayApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return OverlayApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return OverlayApiPigeonCodecWriter(data: data)
  }
}

class OverlayApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = OverlayApiPigeonCodec(readerWriter: OverlayApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OverlayHostApi {
  func initialize() throws
  func showOverlay(request: OverlayRequestDto) throws
  func hideOverlay(request: HideOverlayRequestDto) throws
  func updateSettings(settings: OverlaySettingsDto) throws
  func refreshDisplays() throws
  func getOverlayStatus() throws -> OverlayStatusDto
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OverlayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { OverlayApiPigeonCodec.shared }
  /// Sets up an instance of `OverlayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OverlayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stopgrinding.OverlayHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        do {
          try api.initialize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let showOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stopgrinding.OverlayHostApi.showOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showOverlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! OverlayRequestDto
        do {
          try api.showOverlay(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showOverlayChannel.setMessageHandler(nil)
    }
    let hideOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stopgrinding.OverlayHostApi.hideOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hideOverlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HideOverlayRequestDto
        do {
          try api.hideOverlay(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hideOverlayChannel.setMessageHandler(nil)
    }
    let updateSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stopgrinding.OverlayHostApi.updateSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! OverlaySettingsDto
        do {
          try api.updateSettings(settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateSettingsChannel.setMessageHandler(nil)
    }
    let refreshDisplaysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stopgrinding.OverlayHostApi.refreshDisplays\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshDisplaysChannel.setMessageHandler { _, reply in
        do {
          try api.refreshDisplays()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      refreshDisplaysChannel.setMessageHandler(nil)
    }
    let getOverlayStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stopgrinding.OverlayHostApi.getOverlayStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOverlayStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getOverlayStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getOverlayStatusChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol OverlayFlutterApiProtocol {
  func onOverlayShown(session sessionArg: OverlaySessionDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onOverlayDismissed(event eventArg: OverlayDismissedDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onOverlayFailed(error errorArg: OverlayErrorDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDisplayTopologyChanged(topology topologyArg: DisplayTopologyDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class OverlayFlutterApi: OverlayFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: OverlayApiPigeonCodec {
    return OverlayApiPigeonCodec.shared
  }
  func onOverlayShown(session sessionArg: OverlaySessionDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayShown\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onOverlayDismissed(event eventArg: OverlayDismissedDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayDismissed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onOverlayFailed(error errorArg: OverlayErrorDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onOverlayFailed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDisplayTopologyChanged(topology topologyArg: DisplayTopologyDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.stopgrinding.OverlayFlutterApi.onDisplayTopologyChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([topologyArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
